### ISSUE TITLE
Granting of permissions for new maintainer

### ISSUE THREAD

**Issue by arne48** [ros2-gbp/rqt_console-release#1]
Hello,
In the progress of the [Call for maintainers for some RQt packages!](https://discourse.ros.org/t/call-for-maintainers-for-some-rqt-packages/19827) I took over, among others, the maintenance of this package.
I already got granted access to the packages themselves, but to be able to release a new version, I also need access to this package.

As requested by Katherine_Scott on discourse, I hereby would like to state my status as the current maintainer and would like to request permissions for this package to allow me to release new versions.

Thank you very much in advance.

**Comment by nuclearsandwich** [comment]
You will soon receive an invitation to join the rqt team in this organization. Accepting that invitation will grant you access to this repository as well as several others that you're already a direct contributor on. Once you've accepted the invitation and verified your access please close this issue. Once you've done so, I'll remove the direct collaborator permissions as we're migrating away from those.

**Comment by arne48** [comment]
Thank you very much @nuclearsandwich I now got the invite for ros2-gbp/rqt and I can verify my access to the repositories.
Will I also get an invite to the equivalent in ros-gbp?
The change to teams instead of direct contributors, makes it much easier to organize, so that's a good thing.

**Comment by nuclearsandwich** [comment]
> Will I also get an invite to the equivalent in ros-gbp?

We haven't ported ros-gbp to the new configuration management system that we've just deployed to ros2-gbp. I'll add you as a direct collaborator there for now.

**Comment by arne48** [comment]
Thank you very much for adding me :)
I will close all related issues then.
